val airportCodes = listOf("LAX", "SFO", "PDX", "SEA")

fun getTemperatureAtAirport(code : String ) : String = "${Math.round(Math.random() * 30) + code.count() } C"


// adding map to airport codes, creates a list of pairs. that takes in a code and sets that code to what is generated by getTemperatureAtairport.
// the code -> code is basically : LAX, SFO, PDX, SEAS
// This line uses the map function to create a new list called temperatures. For each airport code in airportCodes,
// it applies a lambda function. The lambda takes an airport code (code) as a parameter and maps it to a pair (code, getTemperatureAtAirport(code))
val temperatures = airportCodes.map { code -> code to getTemperatureAtAirport((code)) }

// println(temperatures)  [(LAX, 31 C), (SFO, 15 C), (PDX, 3 C), (SEA, 4 C)]

for(temp in temperatures){ // you can iterate through a pair and speficy the first and second value.
    println("Airport: ${temp.first} : Temperature: ${temp.second}")
}

// both pair and tripple are immmutable.